## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pass
    url: jdbc:mysql://localhost:3306/shopdb
    platform: mysql
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  servlet:
    contextPath: /api

jwtSecret: com.clothesshop
jwtExpiration: 86400
